[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]==1.9.0",
    "pydantic>=2.11.4",
    "uvicorn>=0.34.2",
]
